name: Project CICD 
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup JDK 18
        uses: actions/setup-java@v2
        with:
          java-version: '18.0.2+101'
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven
        run: mvn clean install
        
