name: CICD Project
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout
        uses: actions/checkout@v2
      - name: Create Maven Build
        run: mvn clean install
      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6.10.0
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/new_demo_app:latest
       - name: Docker Swam deployment
         uses: simbamarufu1/docker-swarm-deploy-action@1.0.3
         with:
          remote_host: ip-172-31-81-161.ec2.interna
          ssh_private_key: ${{ secrets.EC2_PRIVATE_KEY }}
       
        
       
       
      
